language: java
jdk:
  - oraclejdk8
env:
  global:
    - JAVA_OPTS="-Xmx1024M -Xms512M -XX:+UseG1GC"

sudo: false

script: "mvn clean install"

after_success:
  - bash <(curl -s https://codecov.io/bash)